#!/bin/bash

MAKEFILE=Makefile

BUILDFILE=bebnex
MODULE=module

TESTFILE=tebnex
TESTMODULE=testmodule

# is build on win32 platform
GCC_WIN_OPTION=
case $BNX_PLATFORM in 
  "win32") 
    GCC_WIN_OPTION=-lws2_32
esac

# is build debug mode using gdb
GCC_DEBUG_OPTION=
case $BNX_DEBUG in
  "gdb")
    GCC_DEBUG_OPTION=-g
esac

#
# create Makefile
#
cat << END > $MAKEFILE
build: $MODULE
$MODULE:
END

. ./auto/source
# build bebnex
# TODO: set '-lws2_32' after gcc - c hogehoge.c when built on windows
for s in $CORE_SRCS
do
	src=$s

	cat << END >> $MAKEFILE
	gcc -c $src $GCC_WIN_OPTION $GCC_DEBUG_OPTION
END
done

cat << END >> $MAKEFILE
	gcc -o $BUILDFILE [a-zA-Z\_]*\.o $GCC_WIN_OPTION $GCC_DEBUG_OPTION
END

# install, clean
cat << END >> $MAKEFILE
install: $BUILDFILE
	install -s $BUILDFILE $BNX_BUILD_PATH
clean:
	rm -f *\.o $BUILDFILE $TESTFILE
END

cat << END >> $MAKEFILE
$TESTFILE: $TESTMODULE
$TESTMODULE:
END

# build tebnex
for s in $TEST_CORE_SRCS
do
	src=$s
	cat << END >> $MAKEFILE
	gcc -c $src
END
done

cat << END >> $MAKEFILE
	gcc -o $TESTFILE [a-zA-Z\_]*\.o
END

cat << END >> $MAKEFILE
.PHONY: clean install test
END