#!/bin/sh

BNX_CONF_FILE="/etc/bebnex/bebnex.conf"
BNX_BUILD_PATH="/usr/local/bin/"
BNX_ACCESS_LOG_FILE="/var/log/bebnex/bebnex.access.log"
BNX_DEBUG=
USE_IPV6=NO

for options
do
  case $options in
    -*=*)  value=`echo $options | sed -e "s/[-_a-zA-Z0-9]*=//"`  ;;
       *)  value=""  ;;
  esac

  case $options in
    --conf-file=*)  BNX_CONF_FILE=$value  ;;
    --build-path=*) BNX_BUILD_PATH=$value ;;
    --access-log-file=*)   BNX_ACCESS_LOG_FILE=$value   ;;
    --debug=*)  BNX_DEBUG=$value      ;;
    -ipv6) USE_IPV6=YES ;;
  esac
done
